// Generated by tools/audio/voice_parity/generate_profiles.py; do not edit.
export const voiceAudioProfiles = [
  {
    "id": "baseline-128-v1",
    "maxBitrate": 128000,
    "sampleRate": 48000,
    "captureChannels": 1,
    "priority": "high",
    "dtx": true,
    "red": true,
    "forceStereo": false,
    "codec": "opus"
  },
  {
    "id": "speech-64-v1",
    "maxBitrate": 64000,
    "sampleRate": 48000,
    "captureChannels": 1,
    "priority": "high",
    "dtx": true,
    "red": true,
    "forceStereo": false,
    "codec": "opus"
  },
  {
    "id": "speech-96-v1",
    "maxBitrate": 96000,
    "sampleRate": 48000,
    "captureChannels": 1,
    "priority": "high",
    "dtx": true,
    "red": true,
    "forceStereo": false,
    "codec": "opus"
  }
] as const
export const defaultVoiceAudioProfile = "baseline-128-v1"
