"""Exact runtime edges whose configured semantics the operator map documents."""
ANCHORS = (
    ("backend/internal/app/runtime/run.go", "ReadHeaderTimeout: 5 * time.Second", "ReadHeaderTimeout 5 s"),
    ("backend/internal/observability/inspect_readiness/probe.go", "400*time.Millisecond", "400 ms"),
    ("backend/internal/app/observability_routes/readiness_routes.go", "sessionapi.RequireAdministrator(readiness.Handler(service))", "ADMINISTRATOR"),
    ("backend/internal/observability/inspect_readiness/handler.go", 'Set("Cache-Control", "no-store")', "no-store"),
    ("backend/internal/observability/inspect_readiness/handler.go", "http.StatusServiceUnavailable", "503 degraded"),
    ("backend/internal/database/pool/open.go", "pool.Ping(context)", "startup Ping"),
    ("backend/internal/media/dispatch_voice_sfu_revocation/worker.go", "dispatchTimeout    = 5 * time.Second", "dispatch 5 s"),
    ("backend/internal/media/dispatch_voice_sfu_revocation/worker.go", "dispatchBatchLimit = 100", "batch 100"),
    ("backend/internal/media/dispatch_voice_sfu_revocation/repository.go", "interval '15 seconds'", "retry 15 s"),
    ("backend/internal/media/dispatch_voice_sfu_revocation/repository.go", "interval '30 seconds'", "claim 30 s"),
    ("backend/internal/media/dispatch_voice_sfu_revocation/worker/worker.go", "periodic.Start(parent, 15*time.Second", "worker 15 s"),
    ("backend/internal/observability/observe_dependencies/probe.go", "context.WithTimeout(parent, 3*time.Second)", "dependency probe 3 s"),
    ("backend/internal/observability/observe_dependencies/probe.go", "periodic.Start(ctx, 15*time.Second", "probe interval 15 s"),
    ("clients/web/src/voice/connection_deadline.ts", "mediaConnectionTimeoutMs = 20_000", "Web connect 20 s"),
    ("clients/web/src/voice/bounded_voice_reconnect_policy.ts", "context.retryCount >= 6", "web SDK reconnect 6"),
    ("deploy/caddy/Caddyfile", "uri /internal/media-admission", "/internal/media-admission"),
    ("deploy/caddy/Caddyfile", "log_skip @rtc", "log_skip @rtc"),
    ("deploy/livekit/livekit.yaml", "port_range_start: 50000", "UDP 50000–50100"),
    ("deploy/livekit/livekit.yaml", "port_range_end: 50100", "UDP 50000–50100"),
    ("deploy/livekit/livekit.yaml", "tcp_port: 7882", "ICE/TCP 7882"),
    ("backend/internal/observability/start_tracing/provider.go", "sdktrace.WithMaxQueueSize(128)", "trace queue 128"),
    ("backend/internal/observability/start_tracing/provider.go", "sdktrace.WithExportTimeout(3*time.Second)", "trace export 3 s"),
    ("backend/internal/observability/start_metrics/provider.go", "sdkmetric.WithInterval(15*time.Second)", "Metric interval 15 s"),
    ("backend/internal/observability/ingest_client_traces/handler.go", "Timeout: 3 * time.Second", "Relay 3 s"),
    ("docker/observability/collector.yaml", "max_elapsed_time: 30s", "collector retry 30 s"),
    ("docker/observability/collector.yaml", "queue_size: 128", "collector queue 128"),
    ("backend/internal/storage/write_upload/service.go", "MaxBytes int64 = 25_000_000", "25,000,000 bytes"),
    ("backend/internal/realtime/connect_session/connection_contract.go", "defaultSessionRevalidationInterval = 15 * time.Second", "session revalidation 15 s"),
    ("backend/internal/realtime/connect_session/event_stream.go", "context.WithTimeout(context.Background(), 5*time.Second)", "WS write 5 s"),
    ("clients/web/src/realtime/reconnect_policy.ts", "Math.min(15_000, 500 *", "WS reconnect 0.5–15 s"),
)

# These additions invalidate claims of absent configuration and require map review.
FORBIDDEN = (
    ("backend/internal/app/runtime/run.go", "WriteTimeout:"),
    ("backend/internal/app/runtime/run.go", "ReadTimeout:"),
    ("backend/internal/database/pool/open.go", "statement_timeout"),
    ("backend/internal/database/pool/open.go", "connect_timeout"),
    ("deploy/caddy/Caddyfile", "lb_try_duration"),
    ("deploy/caddy/Caddyfile", "lb_retries"),
    ("deploy/livekit/livekit.yaml", "turn:"),
)
