package validate_target

import (
	"context"
	"crypto/tls"
	"errors"
	"net"
	"net/http"
	"net/http/cookiejar"
	"time"
)

// Local fixture TLS is generated by Caddy. Socket destinations stay loopback even
// for localhost, and redirects are refused before any cookie or credential send.
func Client() *http.Client { return ClientFrom(0) }
func ClientFrom(index int) *http.Client {
	jar, _ := cookiejar.New(nil)
	transport := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, MaxConnsPerHost: 4}
	transport.DialContext = func(ctx context.Context, network, address string) (net.Conn, error) {
		host, port, err := net.SplitHostPort(address)
		if err != nil {
			return nil, errors.New("invalid loopback socket")
		}
		if host == "localhost" {
			host = "127.0.0.1"
		}
		ip := net.ParseIP(host)
		if ip == nil || !ip.IsLoopback() {
			return nil, errors.New("non-loopback socket refused")
		}
		dialer := &net.Dialer{Timeout: 3 * time.Second}
		if index > 0 && ip.To4() != nil {
			dialer.LocalAddr = &net.TCPAddr{IP: net.IPv4(127, 0, 0, byte(index+1))}
		}
		return dialer.DialContext(ctx, network, net.JoinHostPort(host, port))
	}
	return &http.Client{Transport: transport, Jar: jar, Timeout: 5 * time.Second, CheckRedirect: func(*http.Request, []*http.Request) error { return errors.New("redirect refused") }}
}
