import { expect, test } from '@playwright/test'
test.beforeEach(async ({ page }) => { await page.goto('/tests/voice_shortcuts/fixture.html'); await page.evaluate(() => localStorage.clear()); await page.reload() })
test('real capture supports physical modifiers, cancel, clear, conflict and reset', async ({ page }) => {
 const assign = page.getByRole('button', { name: 'Назначить сочетание: микрофон', exact: true })
 await assign.click(); await page.keyboard.press('Escape'); await expect(assign).toHaveText('Назначить')
 await assign.click(); await assign.dispatchEvent('keydown', { key:'w',code:'KeyW',ctrlKey:true }); await expect(page.getByRole('alert')).toContainText('зарезервировано')
 await assign.click(); await page.keyboard.press('Control+Alt+m'); await expect(page.getByText('Ctrl+Alt+M', { exact: true })).toBeVisible()
 await page.reload(); await expect(page.getByText('Ctrl+Alt+M', { exact: true })).toBeVisible()
 await page.getByRole('button', { name: 'Назначить сочетание: выключить звук', exact: true }).click(); await page.keyboard.press('Control+Alt+m'); await expect(page.getByRole('alert')).toContainText('уже назначено')
 await assign.click(); await page.keyboard.press('Tab'); await expect(assign).toHaveText('Назначить')
 await assign.click(); await page.keyboard.press('Backspace'); await expect(page.getByText('Ctrl+Alt+M', { exact: true })).toHaveCount(0)
 await assign.click(); await page.keyboard.press('Control+Alt+m'); await page.getByRole('button', { name: 'Сбросить быстрые клавиши' }).click()
 await page.reload(); await expect(page.getByText('Не назначено', { exact: true })).toHaveCount(2)
})
test('real runtime ignores editable, composition, repeat and modal context', async ({ page }) => {
 await page.getByRole('button', { name: 'Назначить сочетание: микрофон', exact: true }).click(); await page.keyboard.press('Control+Alt+m')
 await page.getByRole('textbox', { name: 'Сообщение' }).focus(); await page.keyboard.press('Control+Alt+m'); await expect(page.getByRole('status')).toHaveCount(0)
 await page.getByRole('button', { name: 'Открыть диалог' }).click(); await page.keyboard.press('Control+Alt+m'); await expect(page.getByRole('status')).toHaveCount(0)
 await page.getByRole('button', { name: 'Закрыть', exact: true }).click(); const workspace=page.getByLabel('Рабочая область'); await workspace.focus()
 await workspace.dispatchEvent('keydown', { key:'m',code:'KeyM',ctrlKey:true,altKey:true,isComposing:true }); await expect(page.getByRole('status')).toHaveCount(0)
 await workspace.dispatchEvent('keydown', { key:'m',code:'KeyM',ctrlKey:true,altKey:true,repeat:true }); await expect(page.getByRole('status')).toHaveCount(0)
 await page.keyboard.press('Control+Alt+m'); await expect(page.getByRole('status')).toHaveText('Микрофон включён.')
 await page.keyboard.press('Control+Alt+m'); await expect(page.getByRole('status')).toHaveText('Микрофон выключен.')
})
