import { expect, test } from '@playwright/test'
test.beforeEach(async ({ page }) => { await page.goto('/tests/audio/fixture.html'); await page.waitForFunction(() => 'audioGate' in window) })
const evaluate = (page: any, method: string, value?: string) => page.evaluate(({ method, value }: any) => (window as any).audioGate[method](value), { method, value })
test('scalar WASM graph survives CSP; mute resets DSP and faults silence output', async ({ page, browser }) => {
  const requests: string[] = []; page.on('request', request => requests.push(request.url()))
  const result = await evaluate(page, 'graph')
  expect(result.sampleRate).toBe(48000)
  expect(result.active.some((reading: any) => reading.rms > 0.001)).toBe(true)
  expect(result.active.every((reading: any) => reading.nonfinite === 0 && reading.peak <= 1)).toBe(true)
  expect(result.muted.every((reading: any) => reading.peak === 0)).toBe(true)
  expect(result.afterUnmute.every((reading: any) => reading.peak < 0.0001)).toBe(true)
  expect(result.fault).toEqual({ disabled: true, failures: ['processor-error'] })
  expect(result.states.some((state: any) => state.processedFrames >= 100)).toBe(true)
  expect(requests.every(url => new URL(url).hostname === '127.0.0.1')).toBe(true)
  console.log(JSON.stringify({ gate: 'synthetic-audio-worklet', browser: browser.version(), status: 'PASS', acousticQuality: 'NOT_RUN' }))
})
test('sample rate mismatch and malformed/404 assets fail explicitly', async ({ page, request }) => {
  expect((await evaluate(page, 'invalidRate')).failures).toEqual(['sample-rate'])
  for (const variant of ['html', 'missing', 'bad-model', 'missing-wasm']) expect(await evaluate(page, 'badAsset', `/audio/rnnoise/${variant}/rnnoise-manifest.json`)).toBe(true)
  const wasm = await request.get('/audio/rnnoise/v0.1-cdf196b/rnnoise.wasm')
  expect(wasm.headers()['content-type']).toContain('application/wasm')
  const missing = await request.get('/audio/rnnoise/missing/rnnoise.wasm')
  expect(missing.status()).toBe(404); expect(missing.headers()['content-type']).not.toContain('text/html')
})
test('100 transitions stop derived tracks and preserve borrowed source/context', async ({ page }) => {
  expect(await evaluate(page, 'transitions')).toEqual({ graphs: 100, contextState: 'running', sourceState: 'live' })
  const quantum = await evaluate(page, 'variableQuantum')
  expect(quantum.frames * 480 + quantum.residual).toBe(quantum.samples)
})
test('real WebRTC receiver hears processed synthetic output and mute silence', async ({ page }) => {
  const result = await evaluate(page, 'rtcPair')
  expect(result.sender).toBe('connected'); expect(result.receiver).toBe('connected')
  expect(result.active.some((reading: any) => reading.rms > 0.001)).toBe(true)
  expect(result.muted.length).toBeGreaterThan(0); expect(result.muted.every((reading: any) => reading.peak < 0.0001)).toBe(true)
  console.log(JSON.stringify({ gate: result.path, status: 'PASS', livekitPath: 'NOT_RUN' }))
})
