// Generated by tools/audio/voice_parity/generate_profiles.py; do not edit.
package voiceaudio

var Profiles = map[string]bool{
	"baseline-128-v1": true,
	"speech-64-v1":    true,
	"speech-96-v1":    true,
}
