// Code generated from telemetry-flow-v1.json; DO NOT EDIT.
package flowcontract

const Version = 1

var Operations = map[string]bool{
	"api.request":             true,
	"startup":                 true,
	"session.restore":         true,
	"auth.login":              true,
	"message.send":            true,
	"message.render":          true,
	"voice.join":              true,
	"voice.leave":             true,
	"voice.reconnect":         true,
	"realtime.connect":        true,
	"realtime.reconnect":      true,
	"realtime.process":        true,
	"screen.share.start":      true,
	"screen.share.stop":       true,
	"screen.view":             true,
	"media.sample":            true,
	"audio.input.switch":      true,
	"voice.audio.sample":      true,
	"voice.volume.preference": true,
	"voice.disconnect":        true,
	"telemetry.export.health": true,
}

var Fields = map[string]Field{
	"app.schema.version":                    {Kind: "integer", Min: 1, Max: 1, Values: []string{}},
	"session.id":                            {Kind: "id", Min: 0, Max: 0, Values: []string{}},
	"app.visit.id":                          {Kind: "id", Min: 0, Max: 0, Values: []string{}},
	"app.flow.id":                           {Kind: "id", Min: 0, Max: 0, Values: []string{}},
	"app.media.session.id":                  {Kind: "id", Min: 0, Max: 0, Values: []string{}},
	"app.flow.name":                         {Kind: "enum", Min: 0, Max: 0, Values: []string{"startup", "session.restore", "auth.login", "message.send", "message.render", "voice.join", "voice.leave", "voice.reconnect", "realtime.connect", "realtime.reconnect", "realtime.process", "screen.share.start", "screen.share.stop", "screen.view", "telemetry.export"}},
	"app.flow.stage":                        {Kind: "enum", Min: 0, Max: 0, Values: []string{"intent", "storage", "restore", "authenticate", "workspace", "request", "ack", "render", "lease", "credential", "connect", "microphone", "ready", "select", "subscribe", "track", "decoded", "first_frame", "publish", "stop", "refresh", "dispatch", "enqueue", "dependency", "commit", "authorize", "export"}},
	"app.flow.record":                       {Kind: "enum", Min: 0, Max: 0, Values: []string{"start", "checkpoint", "terminal"}},
	"app.flow.outcome":                      {Kind: "enum", Min: 0, Max: 0, Values: []string{"unknown", "success", "failed", "cancelled", "rejected", "timeout", "superseded"}},
	"app.flow.reason":                       {Kind: "enum", Min: 0, Max: 0, Values: []string{"none", "permission_denied", "network", "dependency", "invalid", "conflict", "deadline", "disposed", "generation_changed", "revoked", "unsupported", "export_lost"}},
	"app.flow.attempt":                      {Kind: "integer", Min: 1, Max: 20, Values: []string{}},
	"app.provenance":                        {Kind: "enum", Min: 0, Max: 0, Values: []string{"client_observed", "server_confirmed", "sfu_observed"}},
	"app.client.version":                    {Kind: "version", Min: 0, Max: 0, Values: []string{}},
	"app.sample.age_ms":                     {Kind: "number", Min: 0, Max: 60000, Values: []string{}},
	"app.sample.window_ms":                  {Kind: "number", Min: 1, Max: 60000, Values: []string{}},
	"app.media.capture_fps":                 {Kind: "number", Min: 0, Max: 240, Values: []string{}},
	"app.media.encoded_fps":                 {Kind: "number", Min: 0, Max: 240, Values: []string{}},
	"app.media.decoded_fps":                 {Kind: "number", Min: 0, Max: 240, Values: []string{}},
	"app.media.presented_fps":               {Kind: "number", Min: 0, Max: 240, Values: []string{}},
	"app.media.bitrate_bps":                 {Kind: "number", Min: 0, Max: 100000000, Values: []string{}},
	"app.media.rtt_ms":                      {Kind: "number", Min: 0, Max: 60000, Values: []string{}},
	"app.media.jitter_ms":                   {Kind: "number", Min: 0, Max: 60000, Values: []string{}},
	"app.media.loss_percent":                {Kind: "number", Min: 0, Max: 100, Values: []string{}},
	"app.media.direction":                   {Kind: "enum", Min: 0, Max: 0, Values: []string{"sender", "receiver"}},
	"app.media.source":                      {Kind: "enum", Min: 0, Max: 0, Values: []string{"webrtc", "presentation", "sfu"}},
	"app.media.target_fps":                  {Kind: "number", Min: 1, Max: 240, Values: []string{}},
	"app.media.sample_state":                {Kind: "enum", Min: 0, Max: 0, Values: []string{"fresh", "stale", "unsupported", "unknown"}},
	"http.request.method":                   {Kind: "enum", Min: 0, Max: 0, Values: []string{"GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "OTHER"}},
	"http.response.status_code":             {Kind: "integer", Min: 100, Max: 599, Values: []string{}},
	"app.storage.result":                    {Kind: "enum", Min: 0, Max: 0, Values: []string{"committed", "replayed", "rejected"}},
	"app.media.adaptation_reason":           {Kind: "enum", Min: 0, Max: 0, Values: []string{"none", "cpu", "bandwidth", "other"}},
	"app.cause.truncated":                   {Kind: "integer", Min: 0, Max: 1000, Values: []string{}},
	"app.voice.mode":                        {Kind: "enum", Min: 0, Max: 0, Values: []string{"participant", "listener", "microphone_unavailable"}},
	"app.export.queued":                     {Kind: "integer", Min: 0, Max: 128, Values: []string{}},
	"app.export.accepted":                   {Kind: "integer", Min: 0, Max: 1000000000000, Values: []string{}},
	"app.export.rejected":                   {Kind: "integer", Min: 0, Max: 1000000000000, Values: []string{}},
	"app.export.dropped":                    {Kind: "integer", Min: 0, Max: 1000000000000, Values: []string{}},
	"app.export.retried":                    {Kind: "integer", Min: 0, Max: 1000000000000, Values: []string{}},
	"app.export.age_ms":                     {Kind: "integer", Min: 0, Max: 86400000, Values: []string{}},
	"app.media.total_bitrate_kbps":          {Kind: "number", Min: 0, Max: 100000, Values: []string{}},
	"app.media.selected_layer_bitrate_kbps": {Kind: "number", Min: 0, Max: 100000, Values: []string{}},
	"app.media.retransmitted_bitrate_kbps":  {Kind: "number", Min: 0, Max: 100000, Values: []string{}},
	"app.media.encode_ms_per_frame":         {Kind: "number", Min: 0, Max: 60000, Values: []string{}},
	"app.media.decode_ms_per_frame":         {Kind: "number", Min: 0, Max: 60000, Values: []string{}},
	"app.media.jitter_buffer_ms_per_frame":  {Kind: "number", Min: 0, Max: 60000, Values: []string{}},
	"app.media.nack_per_second":             {Kind: "number", Min: 0, Max: 1000000, Values: []string{}},
	"app.media.pli_per_second":              {Kind: "number", Min: 0, Max: 1000000, Values: []string{}},
	"app.media.fir_per_second":              {Kind: "number", Min: 0, Max: 1000000, Values: []string{}},
	"app.media.first_frame_ms":              {Kind: "number", Min: 0, Max: 86400000, Values: []string{}},
	"app.media.freeze_duration_ms":          {Kind: "number", Min: 0, Max: 86400000, Values: []string{}},
	"app.media.stats_window_ms":             {Kind: "number", Min: 0.000001, Max: 10000, Values: []string{}},
	"app.media.freeze_count":                {Kind: "integer", Min: 0, Max: 1000000000, Values: []string{}},
	"app.media.collection_state":            {Kind: "enum", Min: 0, Max: 0, Values: []string{"active", "inactive", "sdk_paused", "hidden", "reconnecting", "unavailable", "stale", "unknown", "no_subscriber"}},
	"app.media.presentation_source":         {Kind: "enum", Min: 0, Max: 0, Values: []string{"web_rvfc", "unsupported"}},
	"app.media.stats_source":                {Kind: "enum", Min: 0, Max: 0, Values: []string{"webrtc_interval", "unsupported"}},
}
