"""Generate checked-in adapters; JSON is the only profile source."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[3]
contract = json.loads((root / "contracts/voice-audio-profile.json").read_text(encoding="utf-8"))
header = "// Generated by tools/audio/voice_parity/generate_profiles.py; do not edit.\n"
web = header + "export const voiceAudioProfiles = " + json.dumps(contract["profiles"], indent=2) + " as const\n"
web += "export const defaultVoiceAudioProfile = " + json.dumps(contract["default"]) + "\n"
dart = header + "const voiceAudioProfiles = <Map<String, Object>>" + json.dumps(contract["profiles"], indent=2) + ";\n"
dart += "const defaultVoiceAudioProfile = " + json.dumps(contract["default"]) + ";\n"
go = header + "package voiceaudio\n\nvar Profiles = map[string]bool{\n"
go += "".join('    ' + json.dumps(profile["id"]) + ": true,\n" for profile in contract["profiles"])
go += "}\n"
for name, source in [
    ("clients/web/src/voice/audio_profile/generated.ts", web),
    ("clients/flutter/lib/src/features/voice/audio_profile/generated.dart", dart),
    ("backend/internal/observability/ingest_client_traces/voice_audio/profiles.go", go),
]:
    path = root / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")
